required = [
    "github.com/golangci/golangci-lint/cmd/golangci-lint",
    "github.com/golang/protobuf/protoc-gen-go",
]

[[constraint]]
  name = "github.com/golangci/golangci-lint"
  version = "1.14.1"

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.3.4"

[prune]
  go-tests = true
  unused-packages = true


