// Code generated by protoc-gen-go. DO NOT EDIT.
// source: port-grpc.proto

package portApi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SavePortRequest struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Details              *PortDetails `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SavePortRequest) Reset()         { *m = SavePortRequest{} }
func (m *SavePortRequest) String() string { return proto.CompactTextString(m) }
func (*SavePortRequest) ProtoMessage()    {}
func (*SavePortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_125c66fffefb2210, []int{0}
}

func (m *SavePortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePortRequest.Unmarshal(m, b)
}
func (m *SavePortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePortRequest.Marshal(b, m, deterministic)
}
func (m *SavePortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePortRequest.Merge(m, src)
}
func (m *SavePortRequest) XXX_Size() int {
	return xxx_messageInfo_SavePortRequest.Size(m)
}
func (m *SavePortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SavePortRequest proto.InternalMessageInfo

func (m *SavePortRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SavePortRequest) GetDetails() *PortDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

type SavePortResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SavePortResponse) Reset()         { *m = SavePortResponse{} }
func (m *SavePortResponse) String() string { return proto.CompactTextString(m) }
func (*SavePortResponse) ProtoMessage()    {}
func (*SavePortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_125c66fffefb2210, []int{1}
}

func (m *SavePortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavePortResponse.Unmarshal(m, b)
}
func (m *SavePortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavePortResponse.Marshal(b, m, deterministic)
}
func (m *SavePortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavePortResponse.Merge(m, src)
}
func (m *SavePortResponse) XXX_Size() int {
	return xxx_messageInfo_SavePortResponse.Size(m)
}
func (m *SavePortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SavePortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SavePortResponse proto.InternalMessageInfo

type GetAllPortsRequest struct {
	Cursor               string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPortsRequest) Reset()         { *m = GetAllPortsRequest{} }
func (m *GetAllPortsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPortsRequest) ProtoMessage()    {}
func (*GetAllPortsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_125c66fffefb2210, []int{2}
}

func (m *GetAllPortsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPortsRequest.Unmarshal(m, b)
}
func (m *GetAllPortsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPortsRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPortsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPortsRequest.Merge(m, src)
}
func (m *GetAllPortsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPortsRequest.Size(m)
}
func (m *GetAllPortsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPortsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPortsRequest proto.InternalMessageInfo

func (m *GetAllPortsRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func (m *GetAllPortsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetAllPortsResponse struct {
	Ports                []*PortMap `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllPortsResponse) Reset()         { *m = GetAllPortsResponse{} }
func (m *GetAllPortsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPortsResponse) ProtoMessage()    {}
func (*GetAllPortsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_125c66fffefb2210, []int{3}
}

func (m *GetAllPortsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPortsResponse.Unmarshal(m, b)
}
func (m *GetAllPortsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPortsResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPortsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPortsResponse.Merge(m, src)
}
func (m *GetAllPortsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPortsResponse.Size(m)
}
func (m *GetAllPortsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPortsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPortsResponse proto.InternalMessageInfo

func (m *GetAllPortsResponse) GetPorts() []*PortMap {
	if m != nil {
		return m.Ports
	}
	return nil
}

type PortMap struct {
	Port                 map[string]*PortDetails `protobuf:"bytes,1,rep,name=port,proto3" json:"port,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PortMap) Reset()         { *m = PortMap{} }
func (m *PortMap) String() string { return proto.CompactTextString(m) }
func (*PortMap) ProtoMessage()    {}
func (*PortMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_125c66fffefb2210, []int{4}
}

func (m *PortMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortMap.Unmarshal(m, b)
}
func (m *PortMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortMap.Marshal(b, m, deterministic)
}
func (m *PortMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortMap.Merge(m, src)
}
func (m *PortMap) XXX_Size() int {
	return xxx_messageInfo_PortMap.Size(m)
}
func (m *PortMap) XXX_DiscardUnknown() {
	xxx_messageInfo_PortMap.DiscardUnknown(m)
}

var xxx_messageInfo_PortMap proto.InternalMessageInfo

func (m *PortMap) GetPort() map[string]*PortDetails {
	if m != nil {
		return m.Port
	}
	return nil
}

type PortDetails struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Coordinates          []float32  `protobuf:"fixed32,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	City                 string     `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Province             string     `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	Country              string     `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Alias                []*any.Any `protobuf:"bytes,6,rep,name=alias,proto3" json:"alias,omitempty"`
	Regions              []*any.Any `protobuf:"bytes,7,rep,name=regions,proto3" json:"regions,omitempty"`
	Timezone             string     `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Unlocs               []string   `protobuf:"bytes,9,rep,name=unlocs,proto3" json:"unlocs,omitempty"`
	Code                 string     `protobuf:"bytes,10,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PortDetails) Reset()         { *m = PortDetails{} }
func (m *PortDetails) String() string { return proto.CompactTextString(m) }
func (*PortDetails) ProtoMessage()    {}
func (*PortDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_125c66fffefb2210, []int{5}
}

func (m *PortDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortDetails.Unmarshal(m, b)
}
func (m *PortDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortDetails.Marshal(b, m, deterministic)
}
func (m *PortDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortDetails.Merge(m, src)
}
func (m *PortDetails) XXX_Size() int {
	return xxx_messageInfo_PortDetails.Size(m)
}
func (m *PortDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_PortDetails.DiscardUnknown(m)
}

var xxx_messageInfo_PortDetails proto.InternalMessageInfo

func (m *PortDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PortDetails) GetCoordinates() []float32 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *PortDetails) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PortDetails) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *PortDetails) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *PortDetails) GetAlias() []*any.Any {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *PortDetails) GetRegions() []*any.Any {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *PortDetails) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *PortDetails) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *PortDetails) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*SavePortRequest)(nil), "portApi.SavePortRequest")
	proto.RegisterType((*SavePortResponse)(nil), "portApi.SavePortResponse")
	proto.RegisterType((*GetAllPortsRequest)(nil), "portApi.GetAllPortsRequest")
	proto.RegisterType((*GetAllPortsResponse)(nil), "portApi.GetAllPortsResponse")
	proto.RegisterType((*PortMap)(nil), "portApi.PortMap")
	proto.RegisterMapType((map[string]*PortDetails)(nil), "portApi.PortMap.PortEntry")
	proto.RegisterType((*PortDetails)(nil), "portApi.PortDetails")
}

func init() { proto.RegisterFile("port-grpc.proto", fileDescriptor_125c66fffefb2210) }

var fileDescriptor_125c66fffefb2210 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x25, 0xe9, 0xb6, 0x69, 0x6e, 0xc0, 0x2d, 0x63, 0x91, 0xd9, 0xe8, 0x43, 0xc8, 0x83, 0x04,
	0xc1, 0x2c, 0xd4, 0x17, 0x11, 0x44, 0x2a, 0x8a, 0xbe, 0x2c, 0xe8, 0xec, 0x17, 0x64, 0x93, 0x6b,
	0x19, 0x4c, 0x67, 0xe2, 0xcc, 0xa4, 0x10, 0xbf, 0xc0, 0x4f, 0xf0, 0x37, 0xfc, 0x43, 0x99, 0x99,
	0xa4, 0x76, 0xd7, 0x65, 0x9f, 0x3a, 0xf7, 0xdc, 0x73, 0x4f, 0xef, 0x3d, 0x39, 0x70, 0xde, 0x49,
	0x65, 0x5e, 0xee, 0x54, 0x57, 0x97, 0x9d, 0x92, 0x46, 0x92, 0xc8, 0x02, 0xdb, 0x8e, 0xa7, 0x17,
	0x3b, 0x29, 0x77, 0x2d, 0x5e, 0x3a, 0xf8, 0xa6, 0xff, 0x76, 0x59, 0x89, 0xc1, 0x73, 0xf2, 0xaf,
	0x70, 0x7e, 0x5d, 0x1d, 0xf0, 0x8b, 0x54, 0x86, 0xe1, 0x8f, 0x1e, 0xb5, 0x21, 0x8f, 0x20, 0xe4,
	0x0d, 0x0d, 0xb2, 0xa0, 0x88, 0x59, 0xc8, 0x1b, 0x52, 0x42, 0xd4, 0xa0, 0xa9, 0x78, 0xab, 0x69,
	0x98, 0x05, 0x45, 0xb2, 0x59, 0x97, 0xa3, 0x70, 0x69, 0xc7, 0x3e, 0xf8, 0x1e, 0x9b, 0x48, 0x39,
	0x81, 0xd5, 0x3f, 0x49, 0xdd, 0x49, 0xa1, 0x31, 0x7f, 0x0f, 0xe4, 0x13, 0x9a, 0x6d, 0xdb, 0x5a,
	0x54, 0x4f, 0xff, 0xf4, 0x04, 0x16, 0x75, 0xaf, 0xb4, 0x54, 0x4e, 0x38, 0x66, 0x63, 0x45, 0xd6,
	0x30, 0x6f, 0xf9, 0x9e, 0x1b, 0x3a, 0xcb, 0x82, 0x62, 0xce, 0x7c, 0x91, 0xbf, 0x85, 0xc7, 0xb7,
	0x34, 0xbc, 0x34, 0x79, 0x0e, 0x73, 0xbb, 0x8e, 0xa6, 0x41, 0x36, 0x2b, 0x92, 0xcd, 0xea, 0xd6,
	0x72, 0x57, 0x55, 0xc7, 0x7c, 0x3b, 0xff, 0x15, 0x40, 0x34, 0x42, 0xa4, 0x84, 0x33, 0x0b, 0x8e,
	0x23, 0xe9, 0xdd, 0x11, 0xf7, 0xfb, 0x51, 0x18, 0x35, 0x30, 0xc7, 0x4b, 0xaf, 0x20, 0x3e, 0x42,
	0x64, 0x05, 0xb3, 0xef, 0x38, 0x8c, 0x06, 0xd9, 0x27, 0x79, 0x01, 0xf3, 0x43, 0xd5, 0xf6, 0xf8,
	0xa0, 0x3f, 0x9e, 0xf2, 0x26, 0x7c, 0x1d, 0xe4, 0x7f, 0x42, 0x48, 0x4e, 0x5a, 0x84, 0xc0, 0x99,
	0xa8, 0xf6, 0x38, 0x4a, 0xba, 0x37, 0xc9, 0x20, 0xa9, 0xa5, 0x54, 0x0d, 0x17, 0x95, 0x41, 0xeb,
	0xfc, 0xac, 0x08, 0xd9, 0x29, 0x64, 0xa7, 0x6a, 0x6e, 0x06, 0x67, 0x52, 0xcc, 0xdc, 0x9b, 0xa4,
	0xb0, 0xec, 0x94, 0x3c, 0x70, 0x51, 0x23, 0x3d, 0x73, 0xf8, 0xb1, 0x26, 0x14, 0xa2, 0x5a, 0xf6,
	0xf6, 0x04, 0x3a, 0x77, 0xad, 0xa9, 0xb4, 0xfb, 0x57, 0x2d, 0xaf, 0x34, 0x5d, 0x38, 0x3f, 0xd6,
	0xa5, 0xcf, 0x4b, 0x39, 0xe5, 0xa5, 0xdc, 0x8a, 0x81, 0x79, 0x8a, 0x4d, 0x83, 0xc2, 0x1d, 0x97,
	0x42, 0xd3, 0xe8, 0x01, 0xf6, 0x44, 0xb2, 0x1b, 0x19, 0xbe, 0xc7, 0x9f, 0x52, 0x20, 0x5d, 0xfa,
	0x8d, 0xa6, 0xda, 0x7e, 0xff, 0x5e, 0xb4, 0xb2, 0xd6, 0x34, 0xce, 0x66, 0xf6, 0xfb, 0xfb, 0xca,
	0x5d, 0x26, 0x1b, 0xa4, 0x30, 0x5e, 0x26, 0x1b, 0xdc, 0xfc, 0x0e, 0xbc, 0x67, 0xd7, 0xa8, 0x0e,
	0xbc, 0x46, 0xf2, 0x0e, 0x96, 0x53, 0xca, 0x08, 0x3d, 0x1a, 0x7e, 0x27, 0xcb, 0xe9, 0xc5, 0x3d,
	0x9d, 0x31, 0x37, 0x9f, 0x21, 0x39, 0x89, 0x13, 0x79, 0x7a, 0x64, 0xfe, 0x1f, 0xd4, 0xf4, 0xd9,
	0xfd, 0x4d, 0xaf, 0x74, 0xb3, 0x70, 0x97, 0xbf, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x58,
	0x93, 0x3e, 0x81, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortServiceClient interface {
	SavePort(ctx context.Context, in *SavePortRequest, opts ...grpc.CallOption) (*SavePortResponse, error)
	GetAllPorts(ctx context.Context, in *GetAllPortsRequest, opts ...grpc.CallOption) (*GetAllPortsResponse, error)
}

type portServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortServiceClient(cc *grpc.ClientConn) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) SavePort(ctx context.Context, in *SavePortRequest, opts ...grpc.CallOption) (*SavePortResponse, error) {
	out := new(SavePortResponse)
	err := c.cc.Invoke(ctx, "/portApi.PortService/SavePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) GetAllPorts(ctx context.Context, in *GetAllPortsRequest, opts ...grpc.CallOption) (*GetAllPortsResponse, error) {
	out := new(GetAllPortsResponse)
	err := c.cc.Invoke(ctx, "/portApi.PortService/GetAllPorts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServiceServer is the server API for PortService service.
type PortServiceServer interface {
	SavePort(context.Context, *SavePortRequest) (*SavePortResponse, error)
	GetAllPorts(context.Context, *GetAllPortsRequest) (*GetAllPortsResponse, error)
}

func RegisterPortServiceServer(s *grpc.Server, srv PortServiceServer) {
	s.RegisterService(&_PortService_serviceDesc, srv)
}

func _PortService_SavePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).SavePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portApi.PortService/SavePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).SavePort(ctx, req.(*SavePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_GetAllPorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).GetAllPorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/portApi.PortService/GetAllPorts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).GetAllPorts(ctx, req.(*GetAllPortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "portApi.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SavePort",
			Handler:    _PortService_SavePort_Handler,
		},
		{
			MethodName: "GetAllPorts",
			Handler:    _PortService_GetAllPorts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "port-grpc.proto",
}
